# Generated by Django 4.0 on 2022-01-10 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POIInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30, unique=True)),
                ('desc', models.CharField(default='', max_length=250)),
            ],
            options={
                'db_table': 'poi_interests',
            },
        ),
        migrations.CreateModel(
            name='POIJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30, unique=True)),
                ('desc', models.CharField(default='', max_length=250)),
            ],
            options={
                'db_table': 'poi_jobs',
            },
        ),
        migrations.CreateModel(
            name='POISector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30, unique=True)),
                ('desc', models.CharField(default='', max_length=250)),
            ],
            options={
                'db_table': 'poi_sector',
            },
        ),
        migrations.CreateModel(
            name='POIType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30, unique=True)),
                ('desc', models.CharField(default='', max_length=250)),
            ],
            options={
                'db_table': 'poi_type',
            },
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point', models.FloatField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('poi_intersts', models.ManyToManyField(blank=True, related_name='poi_interests_set', to='company.POIInterests')),
                ('poi_job', models.ManyToManyField(blank=True, related_name='poi_jobs_set', to='company.POIJobs')),
                ('poi_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.poisector')),
                ('poi_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.poitype')),
            ],
            options={
                'db_table': 'poi',
            },
        ),
    ]
