# Generated by Django 4.0 on 2022-01-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_poiinterests_poijobs_poisector_poitype_poi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poi',
            old_name='poi_intersts',
            new_name='poi_interests',
        ),
        migrations.AlterField(
            model_name='poiinterests',
            name='desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='poijobs',
            name='desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='poisector',
            name='desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='poitype',
            name='desc',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
